/*
vpn-indexer

NABU VPN indexer API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiClientListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiClientListRequest{}

// ApiClientListRequest struct for ApiClientListRequest
type ApiClientListRequest struct {
	PaymentKeyHash *string `json:"paymentKeyHash,omitempty"`
}

// NewApiClientListRequest instantiates a new ApiClientListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiClientListRequest() *ApiClientListRequest {
	this := ApiClientListRequest{}
	return &this
}

// NewApiClientListRequestWithDefaults instantiates a new ApiClientListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiClientListRequestWithDefaults() *ApiClientListRequest {
	this := ApiClientListRequest{}
	return &this
}

// GetPaymentKeyHash returns the PaymentKeyHash field value if set, zero value otherwise.
func (o *ApiClientListRequest) GetPaymentKeyHash() string {
	if o == nil || IsNil(o.PaymentKeyHash) {
		var ret string
		return ret
	}
	return *o.PaymentKeyHash
}

// GetPaymentKeyHashOk returns a tuple with the PaymentKeyHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClientListRequest) GetPaymentKeyHashOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentKeyHash) {
		return nil, false
	}
	return o.PaymentKeyHash, true
}

// HasPaymentKeyHash returns a boolean if a field has been set.
func (o *ApiClientListRequest) HasPaymentKeyHash() bool {
	if o != nil && !IsNil(o.PaymentKeyHash) {
		return true
	}

	return false
}

// SetPaymentKeyHash gets a reference to the given string and assigns it to the PaymentKeyHash field.
func (o *ApiClientListRequest) SetPaymentKeyHash(v string) {
	o.PaymentKeyHash = &v
}

func (o ApiClientListRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiClientListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PaymentKeyHash) {
		toSerialize["paymentKeyHash"] = o.PaymentKeyHash
	}
	return toSerialize, nil
}

type NullableApiClientListRequest struct {
	value *ApiClientListRequest
	isSet bool
}

func (v NullableApiClientListRequest) Get() *ApiClientListRequest {
	return v.value
}

func (v *NullableApiClientListRequest) Set(val *ApiClientListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiClientListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiClientListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiClientListRequest(
	val *ApiClientListRequest,
) *NullableApiClientListRequest {
	return &NullableApiClientListRequest{value: val, isSet: true}
}

func (v NullableApiClientListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiClientListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
