/*
vpn-indexer

NABU VPN indexer API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiClientProfileRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiClientProfileRequest{}

// ApiClientProfileRequest struct for ApiClientProfileRequest
type ApiClientProfileRequest struct {
	Id        *string `json:"id,omitempty"`
	Key       *string `json:"key,omitempty"`
	Signature *string `json:"signature,omitempty"`
}

// NewApiClientProfileRequest instantiates a new ApiClientProfileRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiClientProfileRequest() *ApiClientProfileRequest {
	this := ApiClientProfileRequest{}
	return &this
}

// NewApiClientProfileRequestWithDefaults instantiates a new ApiClientProfileRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiClientProfileRequestWithDefaults() *ApiClientProfileRequest {
	this := ApiClientProfileRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApiClientProfileRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClientProfileRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApiClientProfileRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApiClientProfileRequest) SetId(v string) {
	o.Id = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ApiClientProfileRequest) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClientProfileRequest) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ApiClientProfileRequest) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ApiClientProfileRequest) SetKey(v string) {
	o.Key = &v
}

// GetSignature returns the Signature field value if set, zero value otherwise.
func (o *ApiClientProfileRequest) GetSignature() string {
	if o == nil || IsNil(o.Signature) {
		var ret string
		return ret
	}
	return *o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClientProfileRequest) GetSignatureOk() (*string, bool) {
	if o == nil || IsNil(o.Signature) {
		return nil, false
	}
	return o.Signature, true
}

// HasSignature returns a boolean if a field has been set.
func (o *ApiClientProfileRequest) HasSignature() bool {
	if o != nil && !IsNil(o.Signature) {
		return true
	}

	return false
}

// SetSignature gets a reference to the given string and assigns it to the Signature field.
func (o *ApiClientProfileRequest) SetSignature(v string) {
	o.Signature = &v
}

func (o ApiClientProfileRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiClientProfileRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Signature) {
		toSerialize["signature"] = o.Signature
	}
	return toSerialize, nil
}

type NullableApiClientProfileRequest struct {
	value *ApiClientProfileRequest
	isSet bool
}

func (v NullableApiClientProfileRequest) Get() *ApiClientProfileRequest {
	return v.value
}

func (v *NullableApiClientProfileRequest) Set(val *ApiClientProfileRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiClientProfileRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiClientProfileRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiClientProfileRequest(
	val *ApiClientProfileRequest,
) *NullableApiClientProfileRequest {
	return &NullableApiClientProfileRequest{value: val, isSet: true}
}

func (v NullableApiClientProfileRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiClientProfileRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
