/*
vpn-indexer

NABU VPN indexer API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiClientAvailableRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiClientAvailableRequest{}

// ApiClientAvailableRequest struct for ApiClientAvailableRequest
type ApiClientAvailableRequest struct {
	Id *string `json:"id,omitempty"`
}

// NewApiClientAvailableRequest instantiates a new ApiClientAvailableRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiClientAvailableRequest() *ApiClientAvailableRequest {
	this := ApiClientAvailableRequest{}
	return &this
}

// NewApiClientAvailableRequestWithDefaults instantiates a new ApiClientAvailableRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiClientAvailableRequestWithDefaults() *ApiClientAvailableRequest {
	this := ApiClientAvailableRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApiClientAvailableRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClientAvailableRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApiClientAvailableRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApiClientAvailableRequest) SetId(v string) {
	o.Id = &v
}

func (o ApiClientAvailableRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiClientAvailableRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableApiClientAvailableRequest struct {
	value *ApiClientAvailableRequest
	isSet bool
}

func (v NullableApiClientAvailableRequest) Get() *ApiClientAvailableRequest {
	return v.value
}

func (v *NullableApiClientAvailableRequest) Set(
	val *ApiClientAvailableRequest,
) {
	v.value = val
	v.isSet = true
}

func (v NullableApiClientAvailableRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiClientAvailableRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiClientAvailableRequest(
	val *ApiClientAvailableRequest,
) *NullableApiClientAvailableRequest {
	return &NullableApiClientAvailableRequest{value: val, isSet: true}
}

func (v NullableApiClientAvailableRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiClientAvailableRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
