/*
vpn-indexer

NABU VPN indexer API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiRefDataResponsePrice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiRefDataResponsePrice{}

// ApiRefDataResponsePrice struct for ApiRefDataResponsePrice
type ApiRefDataResponsePrice struct {
	Duration *int32 `json:"duration,omitempty"`
	Price    *int32 `json:"price,omitempty"`
}

// NewApiRefDataResponsePrice instantiates a new ApiRefDataResponsePrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiRefDataResponsePrice() *ApiRefDataResponsePrice {
	this := ApiRefDataResponsePrice{}
	return &this
}

// NewApiRefDataResponsePriceWithDefaults instantiates a new ApiRefDataResponsePrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiRefDataResponsePriceWithDefaults() *ApiRefDataResponsePrice {
	this := ApiRefDataResponsePrice{}
	return &this
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *ApiRefDataResponsePrice) GetDuration() int32 {
	if o == nil || IsNil(o.Duration) {
		var ret int32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRefDataResponsePrice) GetDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *ApiRefDataResponsePrice) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int32 and assigns it to the Duration field.
func (o *ApiRefDataResponsePrice) SetDuration(v int32) {
	o.Duration = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *ApiRefDataResponsePrice) GetPrice() int32 {
	if o == nil || IsNil(o.Price) {
		var ret int32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRefDataResponsePrice) GetPriceOk() (*int32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *ApiRefDataResponsePrice) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given int32 and assigns it to the Price field.
func (o *ApiRefDataResponsePrice) SetPrice(v int32) {
	o.Price = &v
}

func (o ApiRefDataResponsePrice) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiRefDataResponsePrice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	return toSerialize, nil
}

type NullableApiRefDataResponsePrice struct {
	value *ApiRefDataResponsePrice
	isSet bool
}

func (v NullableApiRefDataResponsePrice) Get() *ApiRefDataResponsePrice {
	return v.value
}

func (v *NullableApiRefDataResponsePrice) Set(val *ApiRefDataResponsePrice) {
	v.value = val
	v.isSet = true
}

func (v NullableApiRefDataResponsePrice) IsSet() bool {
	return v.isSet
}

func (v *NullableApiRefDataResponsePrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiRefDataResponsePrice(
	val *ApiRefDataResponsePrice,
) *NullableApiRefDataResponsePrice {
	return &NullableApiRefDataResponsePrice{value: val, isSet: true}
}

func (v NullableApiRefDataResponsePrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiRefDataResponsePrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
