/*
vpn-indexer

NABU VPN indexer API

API version: v0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiTxSignupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTxSignupResponse{}

// ApiTxSignupResponse struct for ApiTxSignupResponse
type ApiTxSignupResponse struct {
	TxCbor *string `json:"txCbor,omitempty"`
}

// NewApiTxSignupResponse instantiates a new ApiTxSignupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTxSignupResponse() *ApiTxSignupResponse {
	this := ApiTxSignupResponse{}
	return &this
}

// NewApiTxSignupResponseWithDefaults instantiates a new ApiTxSignupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTxSignupResponseWithDefaults() *ApiTxSignupResponse {
	this := ApiTxSignupResponse{}
	return &this
}

// GetTxCbor returns the TxCbor field value if set, zero value otherwise.
func (o *ApiTxSignupResponse) GetTxCbor() string {
	if o == nil || IsNil(o.TxCbor) {
		var ret string
		return ret
	}
	return *o.TxCbor
}

// GetTxCborOk returns a tuple with the TxCbor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTxSignupResponse) GetTxCborOk() (*string, bool) {
	if o == nil || IsNil(o.TxCbor) {
		return nil, false
	}
	return o.TxCbor, true
}

// HasTxCbor returns a boolean if a field has been set.
func (o *ApiTxSignupResponse) HasTxCbor() bool {
	if o != nil && !IsNil(o.TxCbor) {
		return true
	}

	return false
}

// SetTxCbor gets a reference to the given string and assigns it to the TxCbor field.
func (o *ApiTxSignupResponse) SetTxCbor(v string) {
	o.TxCbor = &v
}

func (o ApiTxSignupResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTxSignupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TxCbor) {
		toSerialize["txCbor"] = o.TxCbor
	}
	return toSerialize, nil
}

type NullableApiTxSignupResponse struct {
	value *ApiTxSignupResponse
	isSet bool
}

func (v NullableApiTxSignupResponse) Get() *ApiTxSignupResponse {
	return v.value
}

func (v *NullableApiTxSignupResponse) Set(val *ApiTxSignupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTxSignupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTxSignupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTxSignupResponse(
	val *ApiTxSignupResponse,
) *NullableApiTxSignupResponse {
	return &NullableApiTxSignupResponse{value: val, isSet: true}
}

func (v NullableApiTxSignupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTxSignupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
