// Copyright 2025 Blink Labs Software
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package api

import (
	"fmt"
	"log/slog"
	"net/http"
	"time"

	_ "github.com/blinklabs-io/vpn-indexer/docs" // docs is generated by Swag CLI
	"github.com/blinklabs-io/vpn-indexer/internal/ca"
	"github.com/blinklabs-io/vpn-indexer/internal/client"
	"github.com/blinklabs-io/vpn-indexer/internal/config"
	"github.com/blinklabs-io/vpn-indexer/internal/database"
	"github.com/blinklabs-io/vpn-indexer/internal/wireguard"
	httpSwagger "github.com/swaggo/http-swagger"
)

const (
	healthcheckPath = "/healthcheck"
)

// Api holds the dependencies for the API server.
type Api struct {
	cfg      *config.Config
	db       *database.Database
	ca       *ca.Ca
	wgClient *wireguard.Client
	s3Client *client.Client
}

// @title			vpn-indexer
// @version		v0
// @description	NABU VPN indexer API
// @BasePath		/
// @contact.name	Blink Labs Software
// @contact.url	https://blinklabs.io
// @contact.email	support@blinklabs.io
//
// @license.name	Apache 2.0
// @license.url	http://www.apache.org/licenses/LICENSE-2.0.html
func Start(
	cfg *config.Config,
	db *database.Database,
	ca *ca.Ca,
	wgClient *wireguard.Client,
	s3Client *client.Client,
) error {
	logger := slog.Default()
	logger.Info("initializing API server")

	api := &Api{
		cfg:      cfg,
		db:       db,
		ca:       ca,
		wgClient: wgClient,
		s3Client: s3Client,
	}

	//
	// Main HTTP server for API endpoints
	//
	mainMux := http.NewServeMux()

	// Healthcheck
	mainMux.HandleFunc(healthcheckPath, api.handleHealthcheck)

	// Swagger
	mainMux.HandleFunc("/swagger/", httpSwagger.WrapHandler)

	// API routes
	mainMux.HandleFunc("/api/client/list", api.handleClientList)
	mainMux.HandleFunc("/api/client/profile", api.handleClientProfile)
	mainMux.HandleFunc("/api/client/available", api.handleClientAvailable)
	mainMux.HandleFunc("/api/refdata", api.handleRefData)
	mainMux.HandleFunc("/api/tx/signup", api.handleTxSignup)
	mainMux.HandleFunc("/api/tx/renew", api.handleTxRenew)
	mainMux.HandleFunc("/api/tx/transfer", api.handleTxTransfer)
	mainMux.HandleFunc("/api/tx/submit", api.handleTxSubmit)

	// WireGuard API routes (only register when both wgClient and s3Client are available)
	if api.wgClient != nil && api.s3Client != nil {
		mainMux.HandleFunc("/api/client/wg-register", api.handleWGRegister)
		mainMux.HandleFunc("/api/client/wg-profile", api.handleWGProfile)
		mainMux.HandleFunc("/api/client/wg-peer", api.handleWGPeer)
		mainMux.HandleFunc("/api/client/wg-devices", api.handleWGDevices)
	} else {
		logger.Warn(
			"WireGuard API routes not registered: wgClient or s3Client is nil",
		)
	}

	// Wrap the mainMux with a CORS middleware
	mainHandler := api.corsMiddleware(mainMux)

	// Start API server
	logger.Info("starting API listener",
		"address", cfg.Api.ListenAddress,
		"port", cfg.Api.ListenPort,
	)
	server := &http.Server{
		Addr: fmt.Sprintf(
			"%s:%d",
			cfg.Api.ListenAddress,
			cfg.Api.ListenPort,
		),
		Handler:           mainHandler,
		ReadHeaderTimeout: 60 * time.Second,
	}
	err := server.ListenAndServe()
	return err
}

// corsMiddleware adds CORS-related headers to every response
func (a *Api) corsMiddleware(
	next http.Handler,
) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().
			Set("Access-Control-Allow-Methods", "GET, POST, DELETE, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "*")

		// Handle CORS preflight requests
		if r.Method == http.MethodOptions {
			w.WriteHeader(http.StatusNoContent)
			return
		}

		next.ServeHTTP(w, r)
	})
}

// handleHealthcheck responds to GET /healthcheck
func (*Api) handleHealthcheck(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	_, _ = w.Write([]byte(`{"healthy": true}`))
}

// handleWGRegister handles POST /api/client/wg-register
// Registers a new WireGuard device for a client
func (a *Api) handleWGRegister(w http.ResponseWriter, r *http.Request) {
	a.wgRegisterImpl(w, r, a.wgClient, a.s3Client)
}

// handleWGProfile handles POST /api/client/wg-profile
// Returns a WireGuard configuration profile for a registered device
func (a *Api) handleWGProfile(w http.ResponseWriter, r *http.Request) {
	a.wgProfileImpl(w, r)
}

// handleWGPeer handles DELETE /api/client/wg-peer
// Removes a WireGuard device registration
func (a *Api) handleWGPeer(w http.ResponseWriter, r *http.Request) {
	a.wgPeerDeleteImpl(w, r, a.wgClient, a.s3Client)
}

// handleWGDevices handles POST /api/client/wg-devices
// Lists all WireGuard devices registered for a client
func (a *Api) handleWGDevices(w http.ResponseWriter, r *http.Request) {
	a.wgDevicesImpl(w, r)
}
