// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Blink Labs Software",
            "url": "https://blinklabs.io",
            "email": "support@blinklabs.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/client/available": {
            "post": {
                "description": "Check if a client profile is available",
                "consumes": [
                    "application/json"
                ],
                "summary": "ClientAvailable",
                "parameters": [
                    {
                        "description": "Client Available Request",
                        "name": "ClientAvailableRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ClientAvailableRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/client/list": {
            "post": {
                "description": "Search for clients matching a given manager public key hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "ClientList",
                "parameters": [
                    {
                        "description": "List Request",
                        "name": "ClientListRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ClientListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of matching clients",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.Client"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/client/profile": {
            "post": {
                "description": "Fetch a client VPN profile given a COSE payload via signed S3 link",
                "consumes": [
                    "application/json"
                ],
                "summary": "ClientProfile",
                "parameters": [
                    {
                        "description": "Profile Request",
                        "name": "ClientProfileRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ClientProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/client/wg-devices": {
            "post": {
                "description": "List all WireGuard devices registered for a client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "WGDevices",
                "parameters": [
                    {
                        "description": "Devices Request",
                        "name": "WGDevicesRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.WGDevicesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Device list",
                        "schema": {
                            "$ref": "#/definitions/api.WGDevicesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/client/wg-peer": {
            "delete": {
                "description": "Remove a WireGuard device registration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "WGPeerDelete",
                "parameters": [
                    {
                        "description": "Delete Request",
                        "name": "WGDeleteRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.WGDeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deletion successful",
                        "schema": {
                            "$ref": "#/definitions/api.WGDeleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/client/wg-profile": {
            "post": {
                "description": "Get a WireGuard configuration profile for a registered device",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain",
                    "application/json"
                ],
                "summary": "WGProfile",
                "parameters": [
                    {
                        "description": "Profile Request",
                        "name": "WGProfileRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.WGProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "WireGuard config file",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden (subscription expired)",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/client/wg-register": {
            "post": {
                "description": "Register a new WireGuard device for a client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "WGRegister",
                "parameters": [
                    {
                        "description": "Register Request",
                        "name": "WGRegisterRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.WGRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Registration successful",
                        "schema": {
                            "$ref": "#/definitions/api.WGRegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request (includes generic error for duplicate pubkey to prevent enumeration)",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden (device limit reached or subscription expired)",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/refdata": {
            "get": {
                "description": "Fetch prices and regions for signup or renewal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "RefData",
                "responses": {
                    "200": {
                        "description": "Prices and regions",
                        "schema": {
                            "$ref": "#/definitions/api.RefDataResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tx/renew": {
            "post": {
                "description": "Build a transaction for a VPN renewal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "TxRenew",
                "parameters": [
                    {
                        "description": "Renewal Request",
                        "name": "TxRenewRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.TxRenewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Built transaction",
                        "schema": {
                            "$ref": "#/definitions/api.TxRenewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tx/signup": {
            "post": {
                "description": "Build a transaction for a VPN signup",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "TxSignup",
                "parameters": [
                    {
                        "description": "Signup Request",
                        "name": "TxSignupRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.TxSignupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Built transaction",
                        "schema": {
                            "$ref": "#/definitions/api.TxSignupResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tx/submit": {
            "post": {
                "description": "Submit a signed transaction to the blockchain",
                "consumes": [
                    "application/cbor"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "TxSubmit",
                "parameters": [
                    {
                        "enum": [
                            "application/cbor"
                        ],
                        "type": "string",
                        "description": "Content type",
                        "name": "Content-Type",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/tx/transfer": {
            "post": {
                "description": "Build a transaction for a VPN transfer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "TxTransfer",
                "parameters": [
                    {
                        "description": "Transfer Request",
                        "name": "TxTransferRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.TxTransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Built transaction",
                        "schema": {
                            "$ref": "#/definitions/api.TxTransferResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Client": {
            "type": "object",
            "properties": {
                "expiration": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                }
            }
        },
        "api.ClientAvailableRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "api.ClientListRequest": {
            "type": "object",
            "properties": {
                "ownerAddress": {
                    "type": "string"
                }
            }
        },
        "api.ClientProfileRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "api.RefDataResponse": {
            "type": "object",
            "properties": {
                "prices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.RefDataResponsePrice"
                    }
                },
                "regions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.RefDataResponsePrice": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                }
            }
        },
        "api.TxRenewRequest": {
            "type": "object",
            "properties": {
                "clientId": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "ownerAddress": {
                    "type": "string"
                },
                "paymentAddress": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                }
            }
        },
        "api.TxRenewResponse": {
            "type": "object",
            "properties": {
                "txCbor": {
                    "type": "string"
                }
            }
        },
        "api.TxSignupRequest": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "integer"
                },
                "ownerAddress": {
                    "type": "string"
                },
                "paymentAddress": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "region": {
                    "type": "string"
                }
            }
        },
        "api.TxSignupResponse": {
            "type": "object",
            "properties": {
                "clientId": {
                    "type": "string"
                },
                "txCbor": {
                    "type": "string"
                }
            }
        },
        "api.TxTransferRequest": {
            "type": "object",
            "properties": {
                "clientId": {
                    "type": "string"
                },
                "ownerAddress": {
                    "type": "string"
                },
                "paymentAddress": {
                    "type": "string"
                }
            }
        },
        "api.TxTransferResponse": {
            "type": "object",
            "properties": {
                "txCbor": {
                    "type": "string"
                }
            }
        },
        "api.WGDeleteRequest": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "wg_pubkey": {
                    "type": "string"
                }
            }
        },
        "api.WGDeleteResponse": {
            "type": "object",
            "properties": {
                "remaining_devices": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "api.WGDeviceInfo": {
            "type": "object",
            "properties": {
                "assigned_ip": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "pubkey": {
                    "type": "string"
                }
            }
        },
        "api.WGDevicesRequest": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                }
            }
        },
        "api.WGDevicesResponse": {
            "type": "object",
            "properties": {
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.WGDeviceInfo"
                    }
                },
                "limit": {
                    "type": "integer"
                }
            }
        },
        "api.WGProfileRequest": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "wg_pubkey": {
                    "type": "string"
                }
            }
        },
        "api.WGRegisterRequest": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "wg_pubkey": {
                    "type": "string"
                }
            }
        },
        "api.WGRegisterResponse": {
            "type": "object",
            "properties": {
                "assigned_ip": {
                    "type": "string"
                },
                "device_count": {
                    "type": "integer"
                },
                "device_limit": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "vpn-indexer",
	Description:      "NABU VPN indexer API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
